<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getVideoComments($id){
        $comments = $this->getEntityManager()->createQuery('
            SELECT c FROM AppBundle:Comment c WHERE c.video = :id ORDER BY c.data DESC
        ')->setParameter('id',$id)->getResult();
        return $comments;
    }
}
